services:
  nodejs:
    container_name: nodejs
    image: node:22
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm start"
    restart: "no"
    networks:
      - bridge
  nginx:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - nodejs
    restart: always
    networks:
      - bridge
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - bridge
  influxdb:
    image: influxdb:1.8
    container_name: influxdb_v1
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: K6
      INFLUXDB_ADMIN_USER: administrator
      INFLUXDB_ADMIN_PASSWORD: administrator
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - bridge
networks:
  bridge:
    driver: bridge